### ISSUE TITLE
I am a noob and I don't know how to run the project

### ISSUE THREAD

**Issue by zemeng2015** [idmillington/cyclone-physics#41]
Hello, I am a new student in Computer Science. I can't run the project I download here. It says that " cannot open source file 'cyclone/body.h' " and I didn't know why. Can anyone help me to solve this problem? I use Window 10 and 64 systems.

**Comment by ButchDean** [comment]
Hi,

Are you loading the project from  the .sln file in cyclone-physics/build/vs2010? I haven't used Windows in a while, but it should work out the box if you have cloned the project exactly as is. Also, is your code from the master branch?

**Comment by RuiMitchellDaSilva** [comment]
I am having a similar problem as well. I am loading the project from the .sln file in cyclone-physics/build/vs2010, but it still comes up with the error: "Error	C1083	Cannot open source file: '..\src\body.cpp': No such file or directory"

Do you need to have Visual Studio 2010 for this to work? At the moment I am using Visual Studio 2015, and I'm not sure since I though older projects can still run on 2015.

**Comment by ButchDean** [comment]
This is happening because of [this change](https://github.com/idmillington/cyclone-physics/commit/498d5389aec03c7eaef20763eb6c8bcc129a3a94). The quickest fix would be to move all the files in cyclone-physics/build/vs2010 up one directory into cyclone-physics/build, or fix the relative paths in your solution. HTH.
